# This file was generated by GoReleaser. DO NOT EDIT.
cask "auxly" do
  version "1.3.1"

  on_macos do
    on_intel do
      sha256 "ebe7977a1950732e6076e6fce3c83ed13fcfc01e235df5485de97e08732b216e"
      url "https://github.com/Tzamun-Arabia-IT-Co/auxly-memory-cli/releases/download/v#{version}/auxly-cli_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d807f461e5a78a2d7a8570c40f4181ce044b65c5588a2545a9ebe649672a318c"
      url "https://github.com/Tzamun-Arabia-IT-Co/auxly-memory-cli/releases/download/v#{version}/auxly-cli_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2d750d5e58c2a472301cc5eeb2cb1fe013d698fc071a90e46b347ddb35aec60e"
      url "https://github.com/Tzamun-Arabia-IT-Co/auxly-memory-cli/releases/download/v#{version}/auxly-cli_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b4944a5adb7f2ca1517967e197211e9e7af3b6f10065ad8281815cf5a9c45a66"
      url "https://github.com/Tzamun-Arabia-IT-Co/auxly-memory-cli/releases/download/v#{version}/auxly-cli_linux_arm64.tar.gz"
    end
  end

  name "auxly"
  desc "Local-first unified memory system for AI agents"
  homepage "https://auxly.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "auxly"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/auxly"]
    end
  end

  # No zap stanza required

end
