# This file was generated by GoReleaser. DO NOT EDIT.
cask "auxly" do
  version "1.1.4"

  on_macos do
    on_intel do
      sha256 "1eb70bf7c2acb4eec28375e6e2920b6f480b4472035171b29f240cdb20ece86b"
      url "https://github.com/Tzamun-Arabia-IT-Co/auxly-memory-cli/releases/download/v#{version}/auxly-cli_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "78345763675baaa232290079c7948f41d345d82abd94e2618dbfd048ea774465"
      url "https://github.com/Tzamun-Arabia-IT-Co/auxly-memory-cli/releases/download/v#{version}/auxly-cli_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9cc62229fa18d41d167c6f8f65a150fe946b1e7c518ada4580c8cb47b49a5b2b"
      url "https://github.com/Tzamun-Arabia-IT-Co/auxly-memory-cli/releases/download/v#{version}/auxly-cli_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "801fdf0e2dcc58f8696b25f0eb9cdcce8d9e2a28b9d361c7a8178c06f25198e8"
      url "https://github.com/Tzamun-Arabia-IT-Co/auxly-memory-cli/releases/download/v#{version}/auxly-cli_linux_arm64.tar.gz"
    end
  end

  name "auxly"
  desc "Local-first unified memory system for AI agents"
  homepage "https://auxly.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "auxly"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/auxly"]
    end
  end

  # No zap stanza required

end
