# This file was generated by GoReleaser. DO NOT EDIT.
cask "auxly" do
  version "1.0.21"

  on_macos do
    on_intel do
      sha256 "7d621ad4c484b08b1789e1cb01613eb550fcdbc369d0927c095ae7ca4f257c94"
      url "https://github.com/Tzamun-Arabia-IT-Co/auxly-memory-cli/releases/download/v#{version}/auxly-cli_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "41bf46247bfa5af61af02695319f27291ad9b2917e70e59cee46176e199cfb2d"
      url "https://github.com/Tzamun-Arabia-IT-Co/auxly-memory-cli/releases/download/v#{version}/auxly-cli_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a28cbfb6e21eeaed3dabb5a2973247b6fb9f37f2d8aa9d39e73dd277f587a461"
      url "https://github.com/Tzamun-Arabia-IT-Co/auxly-memory-cli/releases/download/v#{version}/auxly-cli_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "26078629b6c6c6a033db742ab6ede7167067e6fda882235c81eb609725dedf0e"
      url "https://github.com/Tzamun-Arabia-IT-Co/auxly-memory-cli/releases/download/v#{version}/auxly-cli_linux_arm64.tar.gz"
    end
  end

  name "auxly"
  desc "Local-first unified memory system for AI agents"
  homepage "https://auxly.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "auxly"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/auxly"]
    end
  end

  # No zap stanza required

end
